export const registerPage = {
  modalTitle: '.modal-title',
  agreeButton: 'button.btn.btn-sm.btn-primary.ml-10',
  agreeButtonText: 'Concordo',
  registerClubTitle: 'h3:contains("Registro de Clube")',
  fieldCNPJ: '#cnpjClube',
  searchCNPJButton: '[title="Pesquisar CNPJ"]',
  titleModalInfo: '.swal2-title',
  btnConfirmModal: '.swal2-confirm',
  fieldNameClub: '#nomeCompletoClube',
  fieldSigla: '#siglaClube',
  fieldEmail: '#emailClube',
  fieldFoundationDate: '#dataFundacaoClube',
  fieldPhone: '#telefoneClube',
  fieldCEP: '#cepClube',
  fieldAddress: '#enderecoClube',
  fieldAddressNumber: '#numeroClube',
  fieldNeighborhood: '#bairroClube',
  selectState: '#estadoClube',
  selectCity: '#cidadeClube',
  fielCpf: '#cpfPresidente',
  searchPresidentButton: '[title="Pesquisar CPF Presidente"]',
  fieldNamePresident: '#nomePresidente',
  fieldEmailPresident: '#emailPresidente',
  fieldDateOfBirthPresident: '#dataNascimentoPresidente',
  fieldDateStartTermPresident: '#dataInicioMandatoPresidente',
  fieldPresidentialElectionDate: '#dataEleicaoPresidente',
  fieldDateEndsPresidentMandate: '#dataTerminoMandatoPresidente',
  fieldCpfDirector: '#cpfDiretor',
  searchDirectorButton: '[title="Pesquisar CPF Diretor"]',
  fieldNameDirector: '#nomeDiretor',
  modality: '#modalidade-26',
  agreeSaveButton: 'button.btn.btn-sm.btn-primary.ml-10:contains("Salvar")',
}